### ISSUE TITLE
Too much data...

### ISSUE THREAD

**Issue by dynobo** [kevhen/CryptoCrawler#10]
Hi @kevhen,
Houston, we have a problem. I ran the twitter-listener for two hours on AWS now, and already got 500MB of Data. It's up to 300 Tweets per Minutes for "bitcoin" only. See first stats through jupyter-notebook:

![index](https://user-images.githubusercontent.com/11071876/34394967-7861501c-eb5d-11e7-8421-f5a3babc94ba.png)

Any ideas, where to save data? Even removing "generalcrypto" might not be enough... I can think of two Options:

Option 1:
- Limit number of tweets by filter for: Language, Region, existence of geo coordinates

Option 2:
- Limit amount of data by storing only few selected field of tweets.

PS: Our Data Partition on AWS is 16 GB

**Comment by kevhen** [comment]
I think limiting the region is no option because the currencies are global and so we should use at least all english written tweets.
Wouldn't it be enough to store only the text and the timestamp of the tweets (and maybe the author) or do we need more information? What are you storing at the moment?

**Comment by dynobo** [comment]
Currently everything is store (complete tweet_json).
I would at least keep:
- text
- timestamp
- tweet-id (e.g. to show original tweet in webinterface or identify addtional attributes later)
- geolocation
- author id (might be interesting to see, if only some accounts write all the messages)

But I guess we can decrease volume by ~80% with using these

If we would limit to english language, we would save additional 20-30%. This would also decrease our efforts in text analysis later. But I'm not sure, how much information we loose here...

I start changing to store only the mentioned fields and wait for feedback from you about the language selection.

**Comment by kevhen** [comment]
In my opinion the overhead created by analysing the other languages is not worth the amount of information we gain from it. probably we get everything we need from just English tweets

**Comment by dynobo** [comment]
Perfect. Done in https://github.com/kevhen/CryptoCrawler/pull/11
I'll fetch again some hours of tweets, then let's see what we got :-D

(PS: To get access to aws-vm pls remember to whatsapp me your IP)
