### ISSUE TITLE
Expose Mongo and add credentials

### ISSUE THREAD

**Issue by kevhen** [kevhen/CryptoCrawler#5]
I think we will need to expose the mongo port from the docker container.
Listening to `localhost` will otherwise only work for services running in the same container, but NOT for our other microservices. 

We should expose the port by adding `-p27017:27017` to the docker run command and add credentials to the mongo to secure it from external access.

I can add this in the next days.

**Comment by dynobo** [comment]
Cool, yeah, do this. I'll work on AWS setup, so you can implement it and test it right away on the VM. I'll send you ssh creds as soons as I'm done. See: https://github.com/kevhen/CryptoCrawler/issues/6

**Comment by dynobo** [comment]
just found out: another option would be using the link parameter to make mongo available in other containers.
E.g.: `docker run -t -i --name twitter-listener --link crypto-mongo:mongo [...]`
Then you can use the container name (e.g. crypto-mongo ) as "hostname" to connect to the mongo. Worked for me locally, but I'm fine with both options.

**Comment by kevhen** [comment]
Ah nice! I knew this was possible when using docked compose. But it is great if this also works like that. I will use it as you described

**Comment by dynobo** [comment]
Solved with docker compose networks...
